name: OpenVisusGitHubActions

on: [push]

jobs:

  Win36:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.6' ]   
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Set up CPython
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }} 
        architecture: 'x64'    
    
    - name: Build OpenVisus 
      shell: cmd
      run: |
      	where python \>tmp.txt
      	set /P Python_EXECUTABLE=\<tmp.txt
      	echo %Python_EXECUTABLE%
        set Qt5_DIR=${{ github.workspace }}/Qt/5.9.2/win64_msvc2017_64/lib/cmake/Qt5
        .\scripts\build_win.bat    
    
    
    - name: Install CMake and Swig
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install -y --allow-empty-checksums cmake swig 
            

        
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.9.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        dir: '${{ github.workspace }}/Qt/'
        install-deps: 'true'
    

         
    - name: Install Miniconda 
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        activate-environment: tmp        
        python-version: ${{ matrix.python-version }}

    - name: Build OpenVisus for Conda
      shell: cmd
      run: | 
         conda config --set always_yes yes --set changeps1 no --set anaconda_upload no
         conda install conda-build anaconda-client numpy        
         .\scripts\build_conda.bat



