name: OpenVisusGitHubActions

on: [push]

jobs:

  Win36:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ '3.6' ]   
    steps:
    
    - name: Install Miniconda 
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: 'latest'
        activate-environment: tmp        
        python-version: ${{ matrix.python-version }}

    - name: Build OpenVisus for Conda
      shell: bash -l {0}
      run: | 
         conda info
         conda config --set always_yes yes --set changeps1 no --set anaconda_upload no 
         conda update -q conda 
         conda create -q -n tmp python=${{ matrix.python-version }}  
         conda activate tmp
         conda install conda-build anaconda-client anaconda-client numpy     

         PYTHONPATH=../ python -m OpenVisus configure
         PYTHONPATH=../ python -m OpenVisus test
         PYTHONPATH=../ python -m OpenVisus convert
  
         rm -Rf $(find /Miniconda3 -iname "openvisus*.tar.bz2")	 
         python setup.py -q bdist_conda 
         CONDA_FILENAME=$(find ~/miniconda3 -iname "openvisus*.tar.bz2"  | head -n 1)

         if [[ "${GIT_TAG}" != "" && "${ANACONDA_TOKEN}" != "" ]] ; then
            CONDA_FILENAME=$(find ~/miniconda3 -iname "openvisus*.tar.bz2"  | head -n 1)
            echo "CONDA_FILENAME ${CONDA_FILENAME}"
            anaconda -t "${ANACONDA_TOKEN}" upload "${CONDA_FILENAME}"
         fi
    
    - uses: actions/checkout@v2
    
    - name: Set up CPython
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }} 
        architecture: 'x64'    
    
    - name: Build OpenVisus 
      shell: cmd
      run: |
           set Python_EXECUTABLE=%pythonLocation%\python.exe
           echo %Python_EXECUTABLE%
           %Python_EXECUTABLE% -c "print('Python is working just fine')"
           REM https://github.com/jurplel/install-qt-action set Qt5_DIR 
           REM Qt5_DIR=...
           call .\scripts\build_win.bat  

    - name: Install CMake and Swig
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install -y --allow-empty-checksums cmake swig 

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.9.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        dir: '${{ github.workspace }}/Qt/'
        install-deps: 'true'
         



